/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyeesq;

import javax.swing.JOptionPane;

/**
 *
 * @author XPC
 */

/*
    Frame de interfaz grafica utilizada por el usuario al usar el programa
    
    Al presionar un boton en este frame se hace una invocacion y envia una instruccion
    a la clase de SistemaParqueo. 

    En la clase SistemaParqueo se procesa y guarda toda la informacion.

*/


public class MenuUsuario extends javax.swing.JFrame {


    protected Usuario usuario;


    SistemaParqueo sistema = new SistemaParqueo();
    /**
     * Creates new form MenuUsuario
     * @param usuario
     */
    public MenuUsuario(Usuario usuario) {
        
        initComponents();
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonParquear = new javax.swing.JButton();
        botonTiempo = new javax.swing.JButton();
        botonDesaparcar = new javax.swing.JButton();
        botonReporte = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        AgregarVech2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setText("Sistema de Parqueo");

        botonParquear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonParquear.setText("Parquear");
        botonParquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParquearActionPerformed(evt);
            }
        });

        botonTiempo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonTiempo.setText("Agregar Tiempo");
        botonTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiempoActionPerformed(evt);
            }
        });

        botonDesaparcar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonDesaparcar.setText("Desparcar");
        botonDesaparcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDesaparcarActionPerformed(evt);
            }
        });

        botonReporte.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonReporte.setText("Reporte");
        botonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteActionPerformed(evt);
            }
        });

        botonSalir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        AgregarVech2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AgregarVech2.setText("Agregar Vehiculo ");
        AgregarVech2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVech2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonTiempo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonParquear)
                                .addGap(30, 30, 30)
                                .addComponent(AgregarVech2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(botonDesaparcar)))
                        .addGap(39, 39, 39)
                        .addComponent(botonReporte)
                        .addGap(29, 29, 29)
                        .addComponent(botonSalir)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonParquear)
                    .addComponent(botonDesaparcar)
                    .addComponent(botonReporte)
                    .addComponent(botonSalir)
                    .addComponent(AgregarVech2))
                .addGap(18, 18, 18)
                .addComponent(botonTiempo)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        
            // BOTON SALIR
        
        setVisible(false);
        
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteActionPerformed
        
            // BOTON REPORTES

            sistema.mostrarUSER(usuario.nombreUsuario, usuario.pin, 4);
            JOptionPane.showMessageDialog(null,"Se han generado los reportes");

        
    }//GEN-LAST:event_botonReporteActionPerformed

    private void botonParquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonParquearActionPerformed
        
        // Funcion de parquear
        int choice = 1;
        sistema.mostrarUSER(usuario.nombreUsuario, usuario.pin, choice);
    }//GEN-LAST:event_botonParquearActionPerformed

    private void botonTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiempoActionPerformed
        // Funcion de Agregar Tiempo
        int choice = 2;
        sistema.mostrarUSER(usuario.nombreUsuario, usuario.pin, choice);
    }//GEN-LAST:event_botonTiempoActionPerformed

    private void botonDesaparcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDesaparcarActionPerformed
        // Boton de desaparcar
        int choice = 3;
        sistema.mostrarUSER(usuario.nombreUsuario, usuario.pin, choice);
    }//GEN-LAST:event_botonDesaparcarActionPerformed

    private void AgregarVech2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarVech2ActionPerformed
        // TODO add your handling code here:
        sistema.mostrarUSER(usuario.nombreUsuario, usuario.pin, 6);
        
        
    }//GEN-LAST:event_AgregarVech2ActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarVech2;
    private javax.swing.JButton botonDesaparcar;
    private javax.swing.JButton botonParquear;
    private javax.swing.JButton botonReporte;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
