/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyeesq;
import javax.swing.JOptionPane;
/**
 *
 * @author XPC
 */

/*
    Frame de interfaz grafica utilizada por el usuario al usar el programa
    
    Al presionar un boton en este frame se hace una invocacion y envia una instruccion
    a la clase de SistemaParqueo. 

    En la clase SistemaParqueo se procesa y guarda toda la informacion.

*/

public class MenuAdmin extends javax.swing.JFrame {
    

    protected Usuario usuario;


    SistemaParqueo sistema = new SistemaParqueo();
    
    /**
     * Creates new form MenuAdmin
     * @param usuario
     */
    
    public MenuAdmin(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonConfigParqueo = new javax.swing.JButton();
        botonReportes = new javax.swing.JButton();
        IniciarParqueo = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonRegistroInsp = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido Admin");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setText("Administración del Parqueo");

        botonConfigParqueo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonConfigParqueo.setText("Configuración Parqueo");
        botonConfigParqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfigParqueoActionPerformed(evt);
            }
        });

        botonReportes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonReportes.setText("Reportes");
        botonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportesActionPerformed(evt);
            }
        });

        IniciarParqueo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        IniciarParqueo.setText("Modificar");
        IniciarParqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarParqueoActionPerformed(evt);
            }
        });

        botonSalir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonRegistroInsp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonRegistroInsp.setText("Regitstro de Inspector");
        botonRegistroInsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroInspActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonConfigParqueo)
                        .addGap(29, 29, 29)
                        .addComponent(botonReportes)
                        .addGap(39, 39, 39)
                        .addComponent(IniciarParqueo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(botonSalir)
                        .addGap(103, 103, 103))))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRegistroInsp)
                .addGap(271, 271, 271))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConfigParqueo)
                    .addComponent(botonReportes)
                    .addComponent(IniciarParqueo)
                    .addComponent(botonSalir))
                .addGap(35, 35, 35)
                .addComponent(botonRegistroInsp)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // SALIR
        
         setVisible(false);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonConfigParqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfigParqueoActionPerformed
        // Boton Configurar el Paruqeo
        
        int choice= 1;
        sistema.mostrarAdmin(usuario.nombreUsuario, usuario.pin,choice);
    }//GEN-LAST:event_botonConfigParqueoActionPerformed

    private void botonRegistroInspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroInspActionPerformed
        // Registro de inspector 
        int modo = 2;
        
        RegistroAdminInsp registro  = new RegistroAdminInsp(2);
        registro.setVisible(true);
        registro.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_botonRegistroInspActionPerformed

    private void botonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportesActionPerformed
        
 
        // Boton de reportes
        /*
            Existen 4 opciones
            Reportes generales: Reportes de Administrador y Inspector
            Mostrar todos los espacios: Reporte de espacios del parqueo
            Mostrar solo los espacios ocupados: Reporte de ocupados del parqueo
            Mostrar solo los espacios vacíos: Reporte Espacios vacios del parqueo
        
        */
        String[] options = {"Reportes Generales", "Mostrar todos los espacios","Mostrar solo los espacios ocupados ",
            "Mostrar solo los espacios vacíos ", "Salida"};

        // Mostrar el cuadro de diálogo de opciones
        int choice1 = JOptionPane.showOptionDialog(
                null,
                "Seleccione una opción:",
                "Menú de Opciones",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[0]
        );
        
        if (choice1 == 0) { // Reportes Especificos
            
            sistema.mostrarAdmin(usuario.nombreUsuario, usuario.pin,2); 
            
        } else if (choice1 == 1) { // Mostrar todos los esapcios
            
                
            sistema.mostrarAdmin(usuario.nombreUsuario, usuario.pin,5);   
            
        } else if (choice1 == 2) { //Mostrar solo los espacios ocupados.
            
            sistema.mostrarAdmin(usuario.nombreUsuario, usuario.pin,6); 
            
        } else if(choice1 == 3) { // Mostrar solo los espacios vacíos.
            
            sistema.mostrarAdmin(usuario.nombreUsuario, usuario.pin,7); 
        
        } else if(choice1 == 4){ //Salida
        
        
        }   
        
    }//GEN-LAST:event_botonReportesActionPerformed

    private void IniciarParqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarParqueoActionPerformed
        // TODO add your handling code here:
        
        String[] options = {"Modificar", "Eliminar", "Salida"};

        // Mostrar el cuadro de diálogo de opciones
        int choice = JOptionPane.showOptionDialog(
                null,
                "Seleccione una opción:",
                "Menú de Opciones",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[0]
        );
        
        if (choice == 0) { // Modificar usuario
            
            
            sistema.mostrarAdmin(usuario.nombreUsuario, usuario.pin,3); 
            
        } else if (choice == 1) { // Eliminar usuario
            
                
           sistema.mostrarAdmin(usuario.nombreUsuario, usuario.pin,4); 
            
        } else if (choice == 2) { 
            
            
            
        }
    }//GEN-LAST:event_IniciarParqueoActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IniciarParqueo;
    private javax.swing.JButton botonConfigParqueo;
    private javax.swing.JToggleButton botonRegistroInsp;
    private javax.swing.JButton botonReportes;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
