/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyeesq;

import javax.swing.JOptionPane;

/**
 *
 * @author XPC
 */

/*
    Frame de interfaz grafica utilizada por el usuario al usar el programa
    
    Al presionar un boton en este frame se hace una invocacion y envia una instruccion
    a la clase de SistemaParqueo. 

    En la clase SistemaParqueo se procesa y guarda toda la informacion.

*/
public class MenuInspector extends javax.swing.JFrame {


    protected Usuario usuario;

    SistemaParqueo sistema = new SistemaParqueo();
    
    /**
     * Creates new form MenuInspector
     * @param usuario
     */
    
    public MenuInspector(Usuario usuario) { // Toma datos del usuario
        initComponents();
        this.usuario = usuario; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonRevisar = new javax.swing.JButton();
        botonReportes = new javax.swing.JButton();
        Multar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido Inspector");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setText("Administración del Parqueo");

        botonRevisar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonRevisar.setText("Revisar Parqueo");
        botonRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRevisarActionPerformed(evt);
            }
        });

        botonReportes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonReportes.setText("Reportes");
        botonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportesActionPerformed(evt);
            }
        });

        Multar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Multar.setText("Multar");
        Multar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultarActionPerformed(evt);
            }
        });

        Salir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(botonRevisar)
                        .addGap(39, 39, 39)
                        .addComponent(botonReportes)
                        .addGap(44, 44, 44)
                        .addComponent(Multar)
                        .addGap(43, 43, 43)
                        .addComponent(Salir)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRevisar)
                    .addComponent(botonReportes)
                    .addComponent(Multar)
                    .addComponent(Salir))
                .addGap(127, 127, 127))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        
        // Boton de salir
        setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed

    private void botonRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRevisarActionPerformed
        
        
        // Boton de Revisar
        /*
            Boton con tres opciones
            Revisar Parqueo: Se revisa parqueo actual y se ven las personas multadas
            Revisar multas: Historial de multas
            
        */
        
        String[] options = {"Revisar Parqueo", "Revisar Multas", "Salida"};

        // Mostrar el cuadro de diálogo de opciones
        int choice = JOptionPane.showOptionDialog(
                null,
                "Seleccione una opción:",
                "Menú de Opciones",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[0]
        );
        
        if (choice == 0) { // Revisar Parqueo
            
            
            sistema.mostrarInsp(usuario.nombreUsuario, usuario.pin,1);
            
        } else if (choice == 1) { // Revisar Multas
            
                
           sistema.mostrarInsp(usuario.nombreUsuario, usuario.pin,4); 
            
        }else if(choice == 2){ //Salida
        
        
        }      
        
    }//GEN-LAST:event_botonRevisarActionPerformed

    private void MultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultarActionPerformed
        // TODO add your handling code here:
        
        sistema.mostrarInsp(usuario.nombreUsuario, usuario.pin,3);
    }//GEN-LAST:event_MultarActionPerformed

    private void botonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportesActionPerformed
        // TODO add your handling code here:
        String[] options = {"Reportes Generales", "Mostrar todos los espacios","Mostrar solo los espacios ocupados ",
            "Mostrar solo los espacios vacíos ", "Salida"};

        // Mostrar el cuadro de diálogo de opciones
        int choice2 = JOptionPane.showOptionDialog(
                null,
                "Seleccione una opción:",
                "Menú de Opciones",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[0]
        );
        
        
        
        if (choice2 == 0) {  // Reportes Generales 
            
            sistema.mostrarInsp(usuario.nombreUsuario, usuario.pin,2); 
            
        } else if ( choice2 ==1){ // Mostrar todos los espacios
        
            sistema.mostrarInsp(usuario.nombreUsuario, usuario.pin,5); 
        
        }else if (choice2 == 2) { //Mostrar solo los espacios ocupados.
            
            sistema.mostrarInsp(usuario.nombreUsuario, usuario.pin,6);    
            
        } else if(choice2 == 3) { // Mostrar solo los espacios vacíos.
            
            sistema.mostrarInsp(usuario.nombreUsuario, usuario.pin,7);    
        
        } else if(choice2 == 4){ //Salida
        
        
        }         
    }//GEN-LAST:event_botonReportesActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Multar;
    private javax.swing.JButton Salir;
    private javax.swing.JButton botonReportes;
    private javax.swing.JButton botonRevisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
